src/app.py
from flask import Flask, render_template
import secrets

from src.common import config
from src.common.database import Database
from src.models.deals.deals import Deals
from src.models.deals.views import deals_blueprint
from src.models.users.views import users_blueprint


app = Flask(__name__)
app.config.from_object(config)
app.secret_key = secrets.token_urlsafe()


@app.before_first_request
def database_initialize():
    Database.initialize()


@app.route('/')
def index():
    return render_template('index.html', deals=Deals.featured_deals())


@app.route('/teams')
def teams():
    return render_template('teams.html')


app.register_blueprint(users_blueprint, url_prefix="")
app.register_blueprint(deals_blueprint, url_prefix="")


src/models/deals/views.py
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

from src.models.deals.deals import Deals
import src.models.deals.error as DealError

deals_blueprint = Blueprint('deals', __name__)


@deals_blueprint.route('/upload_deal', methods=['GET', 'POST'])
def upload_deal():
    if request.method == 'POST':
        title = request.form.get("title", None)
        category = request.form.get("category")
        price = request.form.get("price", None)
        link = request.form.get("link", None)
        image = request.files.get("image", None)

        try:
            if Deals.deal_upload(title, category, link, image, price):
                return redirect(url_for('index'))
        except DealError.DealError as e:
            return e.message

    return render_template("add_deal.html")


@deals_blueprint.route('/deals/<string:category>')
def deals_by_category(category):
    deals_data = Deals.search_by_category(category)
    return render_template("deals.html", deals=deals_data)

src/models/users/views.py
from flask import Blueprint, request, session, render_template, url_for
from werkzeug.utils import redirect

from src.models.users.users import Users
import src.models.users.errors as UserErrors


users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user = request.form.get('reg_user', None)
        owner = request.form.get('reg_owner', None)

        if user:
            return redirect(url_for('register_user', user_type='user'))
        elif owner:
            return redirect(url_for("register_user", user_type='owner'))

    return render_template("registration.html")


@users_blueprint.route('/<string:user_type>/register', methods=['GET', 'POST'])
def register_user(user_type):
    if request.method == 'POST':
        username = request.form.get('username', None)
        email = request.form.get('email', None)
        password = request.form.get('password_1', None)
        confirm_pass = request.form.get('password_2', None)
        institution = request.form.get('institution_name', None) if user_type is 'owner' else None
        try:
            if Users.register_user(str(username), str(email), str(password), str(confirm_pass), str(user_type), str(institution)):
                return redirect(url_for('users.login'))
        except UserErrors.UserErrors as e:
            return e.message

    if user_type == 'user':
        return render_template("reg_user.html")
    elif user_type == 'owner':
        return render_template("reg_owner.html")


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = str(request.form.get('username', None))
        password = str(request.form.get('password', None))

        try:
            if Users.login_is_valid(username, password):
                session['username'] = username
                session['logged_in'] = True
                return redirect(url_for("index"))
        except UserErrors.UserErrors as e:
            return e.message

    return render_template("login.html")


@users_blueprint.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for("index"))


@users_blueprint.route('/forgot_password', methods=['GET', 'POST'])
def forgot_pass():
    if request.method == 'POST':
        username = request.form.get('username', None)
        email = request.form.get('email', None)

        try:
            if Users.get_by_email(username, email):
                session['username'] = username
                return redirect(url_for('users.recover_pass', username=username))
        except UserErrors.UserErrors as e:
            return e.message

    return render_template("pass.html")


@users_blueprint.route('/<string:username>/recover_password', methods=['GET', 'POST'])
def recover_pass(username):
    if request.method == 'POST':
        password_1 = request.form.get('password_1', None)
        password_2 = request.form.get('password_2', None)

        try:
            if Users.update_password(username, password_1, password_2):
                return redirect(url_for("users.login"))
        except UserErrors.UserErrors as e:
            return e.message

    return render_template("recover_pass.html")

src/templates/add_deal.html
{% extends "base2.html" %}
{% block content %}
  <div class="header">
    <h2>Deal Upload</h2>
  </div>

  <form method="post" action="{{ url_for('deals.upload_deal') }}" enctype="multipart/form-data">
	
  <div class="input-group">
      <label>Title</label>
      <input type="text" name="title" required>
  </div>

  <div class="input-group">
  <label>Category</label>
  <select name="category" required>
  <option value="text"><strong>Select</strong></option>
  <option value="electronics" name="electronics">Electronics</option>
  <option value="home appliances" name="home appliances">Home Appliances</option>
  <option value="health and beauty" name="health and beauty">Health and Beauty</option>
  <option value="babies and toys" name="babies and toys">Babies and Toys</option>
  <option value="fashion" name="fashion">Fashion</option>
  <option value="bags" name="bags">Bags</option>
  <option value="watches and accessories" name="watches and accessories">Watches and Accessories</option>
  <option value="automobile" name="automobile">Automobile</option>
  <option value="restaurants" name="restaurants">Restaurants</option>
  <option value="travel" name="travel">Travel</option>
  <option value="combo offers" name="combo offers">Combo Offers</option>
  </select> 
  </div>

  <div class="input-group">
      <label>Price</label>
      <input type="text" name="price" required>
  </div>
  <div class="input-group">
      <label>Link</label>
      <input type="url" name="link" required>
  </div>

  <div class="input-group">
    <label>Image</label>
    <input type="file" name="image" required>
  </div>
 

  <div class="input-group">
      <button type="submit" class="btn" name="add_deal">Add Deal</button>
   </div>

  </form>

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Deal Pro</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <link href="{{ url_for('static', filename='assets/img/Logo_small.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/Logo.png') }}" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

  <link href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/ionicons/css/ionicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.csss') }}" rel="stylesheet">

  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>
{% block content %}

{% endblock %}

  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-4 footer-info">
            <img src="{{ url_for('static', filename='assets/img/Logo.png') }}">
            <p>The world is moving at a very fast pace. Connectivity is a huge thing in the present world. Those who can connect more, can grasp more, gain more foothold. We opt to help you gain that foothold. We help bring all sorts of deals needed for your daily lives closer to you, in one compact package.</p>
          </div>

          <div class="col-lg-4 col-md-4 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="{{ url_for('teams') }}">About us</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-4 footer-contact">
            <h4>Contact Us</h4>
            <p>
              <strong>Phone:</strong> +880 1631340033, +880 1845616466<br>
              <strong>Email:</strong> mohammadmuntasir96@gmail.com, imranulashrafi@outlook.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>Deal Pro</strong>. All Rights Reserved
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <script src="{{ url_for('static', filename='lib/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/jquery/jquery-migrate.min.js') }}"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/superfish/hoverIntent.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/superfish/superfish.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/counterup/counterup.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/isotope/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/touchSwipe/jquery.touchSwipe.min.js') }}"></script>

  <script src="{{ url_for('static', filename='contactform/contactform.js') }}"></script>

  <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>
</html>

src/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deal Pro</title>

    <link href="{{ url_for('static', filename='assets/img/Logo_small.png') }}" rel="icon">
    <link href="{{ url_for('static', filename='assets/img/Logo.png') }}" rel="apple-touch-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/front.css') }}">

</head>
<body>
{% block content%}

{% endblock %}
</body>
</html>

src/templates/deals.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Deal Pro</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <link href="{{ url_for('static', filename='assets/img/Logo_small.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/Logo.png') }}" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

  <link href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/ionicons/css/ionicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.csss') }}" rel="stylesheet">

  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/style2.css') }}" rel="stylesheet">
</head>

<body>
  <header id="header">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
        <a href="{{ url_for('index') }}"><img src="{{ url_for('static', filename='assets/img/Logo.png') }}" alt="" title="" /></a>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-has-children"><a href="">Categories</a>
            <ul>
              <li><a href="{{ url_for('deals.deals_by_category', category='electronics') }}">Electronics</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='home appliances') }}">Home Appliances</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='health and beauty') }}">Health and Beauty</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='babies and toys') }}">Babies and Toys</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='fashion') }}">Fashion</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='bags') }}">Bags</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='watches and accessories') }}">Watches and accessories</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='automobile') }}">Automobile</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='restaurants') }}">Restaurants</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='travel') }}">Travel</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='combo offers') }}">Combo Offers</a></li>
            </ul>
          </li>
          <li id="search-box">
            <form action="deals.html" method="post">
              <input type="text" placeholder="Search">
              <button type="submit">
                <i class="fa fa-search"></i>
              </button>
            </form>
          </li>
          {% if session['logged_in'] == True %}
            <li class="menu-has-children"><a href="#">{{ session['username'] }}</a>
              <ul>
                  <li><a href="#">Upload Deals</a></li>
                  <li><a href="#">Logout</a></li>
                </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('users.login') }}">Login</a></li>
            <li><a href="{{ url_for('users.register')}}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>
  <main>
    {% for deal in deals%}
      <section id="featured">
        <div class="container">
          <div class="featured-row wow fadeInUp">
            <div class="img">
              <img src="{{ url_for('static', filename='assets/deals/' + deal.image) }}" alt="" class="img-fluid">
            </div>
            <div>
              <h2 class="title">{{ deal.title }}</h2>
              <p>
                Price: {{ deal.price }}
              </p>
              <div class="icon"><a href="{{ deal.link }}"><i class="ion-ios-eye-outline"></i></a></div>
            </div>
          </div>
        </div>
      </section>
    {% endfor %}
  </main>

  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-4 footer-info">
            <img src="{{ url_for('static', filename='assets/img/Logo.png') }}">
            <p>The world is moving at a very fast pace. Connectivity is a huge thing in the present world. Those who can connect more, can grasp more, gain more foothold. We opt to help you gain that foothold. We help bring all sorts of deals needed for your daily lives closer to you, in one compact package.</p>
          </div>

          <div class="col-lg-4 col-md-4 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="{{ url_for('teams') }}">About us</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-4 footer-contact">
            <h4>Contact Us</h4>
            <p>
              <strong>Phone:</strong> +880 1631340033, +880 1845616466<br>
              <strong>Email:</strong> mohammadmuntasir96@gmail.com, imranulashrafi@outlook.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>Deal Pro</strong>. All Rights Reserved
      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <script src="{{ url_for('static', filename='lib/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/jquery/jquery-migrate.min.js') }}"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/superfish/hoverIntent.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/superfish/superfish.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/counterup/counterup.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/isotope/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/touchSwipe/jquery.touchSwipe.min.js') }}"></script>

  <script src="{{ url_for('static', filename='contactform/contactform.js') }}"></script>

  <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% block content%}
  <header id="header">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
        <a href="{{ url_for('index') }}"><img src="{{ url_for('static', filename='assets/img/Logo.png') }}" alt="" title="" /></a>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li><a href="#featured">Featured Deals</a></li>
          <li class="menu-has-children"><a href="">Categories</a>
            <ul>
              <li><a href="{{ url_for('deals.deals_by_category', category='electronics') }}">Electronics</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='home appliances') }}">Home Appliances</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='health and beauty') }}">Health and Beauty</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='babies and toys') }}">Babies and Toys</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='fashion') }}">Fashion</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='bags') }}">Bags</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='watches and accessories') }}">Watches and accessories</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='automobile') }}">Automobile</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='restaurants') }}">Restaurants</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='travel') }}">Travel</a></li>
              <li><a href="{{ url_for('deals.deals_by_category', category='combo offers') }}">Combo Offers</a></li>
            </ul>
          </li>
          <li id="search-box">
            <form action="" method="post">
              <input type="text" placeholder="Search">
              <button type="submit">
                <i class="fa fa-search"></i>
              </button>
            </form>
          </li>
          {% if session['logged_in'] == True %}
            <li class="menu-has-children"><a href="#">{{ session['username'] }}</a>
              <ul>
                  <li><a href="{{ url_for('deals.upload_deal') }}">Upload Deals</a></li>
                  <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('users.login') }}">Login</a></li>
            <li><a href="{{ url_for('users.register') }}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel slide carousel-fade" data-ride="carousel">
        <video width="100%" height="100%" autoplay loop muted>
            <source src="{{ url_for('static', filename='assets/video/Video.mp4') }}" type="video/mp4">
        </video>
      </div>
    </div>
  </section>

  <main id="main">

    <section id="featured" class="app">
      <div class="container">

        <header class="section-header">
          <h3>Featured Deals</h3>
          <p></p>
        </header>

        <div class="row hs full">

          {% for deal in deals %}
            <div class="wow fadeInUp">
              <div class="featured-col">
                <div class="img">
                  <img src="{{ url_for('static', filename='assets/deals/' + deal.image) }}" alt="" class="img-fluid">
                  <div class="icon"><a href="{{ deal.link }}"><i class="ion-ios-speedometer-outline"></i></a></div>
                </div>
                <h2 class="title">{{ deal.title }}</h2>
                <p>
                 Price: {{ deal.price }}
                </p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </main>

{% endblock %}

src/templates/login.html
{% extends "base2.html" %}
{% block content%}
  <div class="header">
    <h2>Login</h2>
  </div>  
  
    <form method="post" action="{{ url_for('users.login') }}">

    <div class="input-group">
        <label>Username</label>
        <input type="text" name="username" >
    </div>
    <div class="input-group">
        <label>Password</label>
        <input type="password" name="password">
    </div>
    <div class="input-group">
        <button type="submit" class="btn" name="login_user">Login</button>
    </div>
    <p>
        Don't have an account? <a href="{{ url_for('users.register') }}">Sign up Here</a>
    </p>
    <p>
        Forgot password? <a href="{{ url_for('users.forgot_pass') }}">Click Here</a>
    </p>
   
  </form>
{% endblock %}

src/templates/pass.html
{% extends "base2.html" %}
{% block content %}
<div class="header">
    <h2>Recover Your Password</h2>
</div>

<form method="post" action= "{{ url_for('users.forgot_pass') }}">
  Enter Your Information to get a recovery link:<br>
  <div class="input-group">
      <label>Username</label>
      <input type="text" name="username" required>
  </div>
    <div class="input-group">
        <label>Email</label>
        <input type="email" name="email" required>
    </div>
  <div class="input-group">
      <button type="submit" class="btn" name="submit">Submit</button>
  </div>
</form>
{% endblock %}

src/templates/recover_pass.html
{% extends "base2.html" %}
{% block content %}
<div class="header">
    <h2>Recover Your Password</h2>
</div>

<form method="post" action= "{{ url_for('users.recover_pass', username=session.get('username', None)) }}">
  <div class="input-group">
    <label>New Password</label>
    <input type="password" name="password_1" required>
  </div>

  <div class="input-group">
    <label>Confirm Password</label>
    <input type="password" name="password_2" required>
  </div>
  <div class="input-group">
    <button type="submit" class="btn" name="submit">Submit</button>
  </div>
</form>
{% endblock %}

src/templates/reg_owner.html
{% extends "base2.html" %}
{% block content%}
  <div class="header">
    <h2>Sign Up Form</h2>
    <p>Please fill in this form to create an account</p>
  </div>
  
  <form method="post" action="{{ url_for('users.register_user', user_type='owner') }}">
  
    <div class="input-group">
      <label>Username</label>
      <input type="text" name="username" required>
    </div>

    <div class="input-group">
      <label>Email</label>
      <input type="email" name="email" required>
    </div>

    <div class="input-group">
      <label>Institution Name</label>
      <input type="text" name="institution_name" required>
    </div>

    <div class="input-group">
      <label>Password</label>
      <input type="password" name="password_1" required>
    </div>

    <div class="input-group">
      <label>Confirm password</label>
      <input type="password" name="password_2" required>
    </div>

    <div class="input-group">
      <button type="submit" class="btn" name="reg_user">Sign Up</button>
    </div>

    <p>
      By creating an account you agree to our <a href="#">Terms & Privacy</a>.
    </p>

    <p>
      Already a member? <a href="{{ url_for('users.login') }}">Sign in here</a>
    </p>
    
  </form>
{% endblock %}

src/templates/reg_user.html
{% extends "base2.html" %}
{% block content%}
  <div class="header">
    <h2>Sign Up Form</h2>
    <p>Please fill in this form to create an account</p>
  </div>
  
  <form method="post" action="{{ url_for('users.register_user', user_type='user') }}">
  
    <div class="input-group">
      <label>Username</label>
      <input type="text" name="username" required>
    </div>

    <div class="input-group">
      <label>Email</label>
      <input type="email" name="email" required>
    </div>

    <div class="input-group">
      <label>Password</label>
      <input type="password" name="password_1" required>
    </div>

    <div class="input-group">
      <label>Confirm password</label>
      <input type="password" name="password_2" required>
    </div>

    <div class="input-group">
      <button type="submit" class="btn" name="reg_user">Sign Up</button>
    </div>

    <p>
      By creating an account you agree to our <a href="#">Terms & Privacy</a>.
    </p>

    <p>
      Already a member? <a href="{{ url_for('users.login') }}">Sign in here</a>
    </p>
    
  </form>
{% endblock %}

src/templates/registration.html
{% extends "base2.html" %}
{% block content%}
  <div class="header">
    <h2>Sign Up As</h2>
  </div>
  <form method="post" action="{{ url_for('users.register') }}">

    <select name="Sign Up" onchange="location = this.value;">

<<<<<<< HEAD
    <option value="text">Sign Up</option> 
    <option value="{{ url_for('users.register_user', user_type='user')}}">Sign Up As User</option>
    <option value="{{ url_for('users.register_user', user_type='owner')}}">Sign Up As Owner</option>
=======
>>>>>>> master

    </select>

  </form>
{% endblock %}